// <auto-generated />
using System;
using CovidDailyCases.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CovidDailyCases.API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("CovidDailyCases.API.Models.Cases", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Variant")
                        .HasColumnType("TEXT");

                    b.Property<int>("numSequences")
                        .HasColumnType("INTEGER");

                    b.Property<int>("numSequencesTotal")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("percSequences")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("cases");
                });
#pragma warning restore 612, 618
        }
    }
}
